{
 "title": "Traefik Metrics",
 "description": "Traefik metrics from Influxdb database",
 "tags": [ "www" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "backend",
    "label": "Backend",
    "query": "select * from \"traefik.backend.requests.total\""
   },
   { "name": "sampling", "label": "Sampling", "query": "1m,10m,60m" }
  ]
 },
 "panels": [
  {
   "title": "Total request",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "traefik.backend.requests.total",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "backend", "operator": "=~", "value": "/^$backend$/" }
     ]
    }
   ]
  },
  {
   "title": "Total status code count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_code",
     "groupBy": [
      { "params": [ "code" ], "type": "tag" }
     ],
     "measurement": "traefik.backend.requests.total",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "backend", "operator": "=~", "value": "/^$backend$/" }
     ]
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_backend",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "backend" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "traefik.backend.request.duration",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "backend", "operator": "=~", "value": "/^$backend$/" }
     ]
    }
   ]
  },
  {
   "title": "Access by backends",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_backend",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "backend" ], "type": "tag" }
     ],
     "measurement": "traefik.backend.requests.total",
     "query": "SELECT sum(\"count\") FROM \"traefik.backend.requests.total\" WHERE $timeFilter GROUP BY time($__interval), \"backend\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "backend", "operator": "=~", "value": "/^$backend$/" }
     ]
    }
   ]
  }
 ]
}